import { heroById } from "../../data/heroes";
import type { DotaTeam, MatchAnalysisEvent, MatchFarmWindow, MatchMapAnalysis, MatchMapPoint, MatchMinuteSnapshot, MatchObjectiveEvent } from "../types";

type Raw=Record<string,unknown>;
const INVIS_HEROES=new Map<number,string>([[9,"Mirana"],[16,"Sand King"],[32,"Riki"],[46,"Templar Assassin"],[56,"Clinkz"],[62,"Bounty Hunter"],[63,"Weaver"],[74,"Invoker"],[83,"Treant Protector"],[88,"Nyx Assassin"],[93,"Slark"]]);
const NATURAL_REVEAL=new Map<number,string>([[22,"Zeus"],[28,"Slardar"]]);
const record=(value:unknown):Raw|null=>value&&typeof value==="object"&&!Array.isArray(value)?value as Raw:null;
const records=(value:unknown)=>Array.isArray(value)?value.map(record).filter((item):item is Raw=>Boolean(item)):[];
const num=(value:unknown)=>typeof value==="number"&&Number.isFinite(value)?value:null;
const str=(value:unknown)=>typeof value==="string"&&value.trim()?value.trim():null;
const eventTime=(entry:Raw)=>num(entry.time)??num(entry.timestamp)??0;
const coord=(value:number)=>Math.max(0,Math.min(100,value>100?value/255*100:value));
const percentage=(value:number,total:number)=>total>0?Math.round(value/total*100):null;

function purchaseEntries(player:Raw){return records(player.purchase_log).flatMap((entry)=>{const key=(str(entry.key)||"").replace(/^item_/,"");const second=Math.max(0,eventTime(entry));return key?[{key,second,minute:Math.floor(second/60)}]:[];});}
function countPurchase(player:Raw,...keys:string[]){const purchases=record(player.purchase);const count=keys.reduce((sum,key)=>sum+(num(player[`purchase_${key}`])??num(purchases?.[key])??0),0);return count||purchaseEntries(player).filter((entry)=>keys.includes(entry.key)).length;}
function firstPurchaseSecond(player:Raw,...keys:string[]){const values=purchaseEntries(player).filter((entry)=>keys.includes(entry.key)).map((entry)=>entry.second);return values.length?Math.min(...values):null;}
function levelSixMinute(player:Raw){const xp=Array.isArray(player.xp_t)?player.xp_t.map(num):[];const minute=xp.findIndex((value)=>value!==null&&value>=2_400);return minute>=0?minute:null;}
function teamOf(player:Raw):DotaTeam|null{const slot=num(player.player_slot);return slot===null?null:slot<128?"radiant":"dire";}

interface WardLife {start:number;end:number;seconds:number;x:number|null;y:number|null;}
function wardLives(player:Raw){const removed=new Map(records(player.obs_left_log).flatMap((entry)=>num(entry.ehandle)===null||num(entry.time)===null?[]:[[num(entry.ehandle) as number,num(entry.time) as number] as const]));return records(player.obs_log).flatMap((entry):WardLife[]=>{const handle=num(entry.ehandle),start=num(entry.time),end=handle===null?null:removed.get(handle)??null;if(start===null||end===null||end<start)return[];return[{start,end,seconds:end-start,x:num(entry.x),y:num(entry.y)}];});}

export function playerEvents(player:Raw,allPlayers:Raw[],heroId:number,team:DotaTeam):MatchAnalysisEvent[]{
  const events:MatchAnalysisEvent[]=[];
  const add=(source:unknown,type:MatchAnalysisEvent["type"],label:string,positive:boolean|null)=>records(source).forEach((entry,index)=>{const second=Math.max(0,eventTime(entry)),key=str(entry.key)||label;events.push({id:`${type}-${second}-${index}-${key}`,minute:Math.floor(second/60),second,type,label:key.replace(/^item_/,"").replaceAll("_"," "),x:num(entry.x),y:num(entry.y),positive});});
  add(player.kills_log,"kill","Kill",true);add(player.deaths_log,"death","Death",false);add(player.buyback_log,"buyback","Buyback",null);add(player.obs_log,"ward","Observer Ward",true);add(player.sen_log,"sentry","Sentry Ward",true);
  purchaseEntries(player).forEach((entry,index)=>{const type=entry.key.includes("smoke")?"smoke":entry.key.includes("dust")?"dust":"item";events.push({id:`${type}-${entry.second}-${index}`,minute:entry.minute,second:entry.second,type,label:entry.key.replaceAll("_"," ")});});
  if(!events.some((entry)=>entry.type==="death")){const slug=heroById(heroId)?.slug.replaceAll("-","_").toLowerCase();if(slug)allPlayers.forEach((opponent,opponentIndex)=>{if(teamOf(opponent)===team)return;records(opponent.kills_log).forEach((entry,index)=>{const victim=(str(entry.key)||"").toLowerCase();if(!victim.endsWith(slug)&&!victim.includes(`hero_${slug}`))return;const second=Math.max(0,eventTime(entry));events.push({id:`death-${opponentIndex}-${second}-${index}`,minute:Math.floor(second/60),second,type:"death",label:"Death",detail:"از Kill log تیم حریف استخراج شد",positive:false});});});}
  return events.sort((left,right)=>left.second-right.second);
}

function lanePoints(player:Raw,type:"movement"|"farm"="movement"):MatchMapPoint[]{const lane=record(player.lane_pos);if(!lane)return[];return Object.entries(lane).flatMap(([xKey,value])=>{const nested=record(value);if(nested)return Object.entries(nested).flatMap(([yKey,weight])=>Number.isFinite(Number(xKey))&&Number.isFinite(Number(yKey))&&num(weight)!==null?[{x:coord(Number(xKey)),y:100-coord(Number(yKey)),minute:null,weight:num(weight) as number,type}]:[]);const match=/(-?\d+(?:\.\d+)?)[,|:](-?\d+(?:\.\d+)?)/.exec(xKey);return match&&num(value)!==null?[{x:coord(Number(match[1])),y:100-coord(Number(match[2])),minute:null,weight:num(value) as number,type}]:[];});}
function closest(timeline:MatchMinuteSnapshot[],minute:number){return[...timeline].reverse().find((point)=>point.minute<=minute);}
function median(values:number[]){if(!values.length)return 0;const sorted=[...values].sort((a,b)=>a-b),middle=Math.floor(sorted.length/2);return sorted.length%2?sorted[middle]:(sorted[middle-1]+sorted[middle])/2;}
function farmWindows(timeline:MatchMinuteSnapshot[],events:MatchAnalysisEvent[],duration:number):MatchFarmWindow[]{const borders=[0,5,10,20,30,40,60].filter((minute)=>minute<duration);if(borders.at(-1)!==duration)borders.push(duration);const gains=timeline.map((point)=>point.goldDelta).filter((value):value is number=>value!==null&&value>0),typical=median(gains);return borders.slice(0,-1).map((from,index)=>{const to=borders[index+1],start=closest(timeline,from),end=closest(timeline,to),lastHits=start?.lastHits!==null&&start?.lastHits!==undefined&&end?.lastHits!==null&&end?.lastHits!==undefined?end.lastHits-start.lastHits:null,netWorth=end?.gold??null,xp=end?.xp??null,farmGain=start?.gold!==null&&start?.gold!==undefined&&end?.gold!==null&&end?.gold!==undefined?end.gold-start.gold:null,deaths=events.filter((event)=>event.type==="death"&&event.minute>=from&&event.minute<to).length,expected=typical*Math.max(1,to-from),ratio=farmGain===null||!expected?1:farmGain/expected,state=deaths&&ratio<.75?"setback":ratio>=1.2?"surge":ratio>=.85?"progress":ratio<.55?"out":"steady";return{from,to,lastHits,netWorth,xp,farmGain,deaths,state,note:deaths?`${deaths} Death هم‌زمان با این بازه ثبت شده؛ افت Farm می‌تواند با زمان مرده مرتبط باشد.`:ratio<.75?"ریتم دریافت Gold نسبت به میانه شخصی Match افت کرده است.":"ریتم Farm در این بازه پایدار یا رو به رشد بوده است."};});}
function recovery(timeline:MatchMinuteSnapshot[]){const setbacks=timeline.filter((point)=>point.state==="setback"||point.state==="out");if(!setbacks.length)return null;return Math.round(setbacks.filter((point)=>timeline.some((next)=>next.minute>point.minute&&next.minute<=point.minute+5&&(next.state==="progress"||next.state==="surge"))).length/setbacks.length*100);}

function objectiveKind(name:string):MatchObjectiveEvent["type"]{return name.includes("roshan")?"roshan":name.includes("tower")?"tower":name.includes("barrack")?"barracks":"other";}
function objectiveAnalysis(rawMatch:Raw,player:Raw,allPlayers:Raw[],team:DotaTeam,events:MatchAnalysisEvent[]){
  const teamSlots=new Set(allPlayers.flatMap((entry)=>{const slot=num(entry.player_slot);return slot!==null&&teamOf(entry)===team?[slot]:[];}));const objectives=records(rawMatch.objectives).filter((entry)=>{const slot=num(entry.player_slot)??num(entry.slot);if(slot!==null)return teamSlots.has(slot);const eventTeam=num(entry.team);return eventTeam===null||eventTeam===(team==="radiant"?0:1);});const teamKills=allPlayers.filter((entry)=>teamOf(entry)===team).flatMap((entry)=>records(entry.kills_log).map(eventTime)).sort((a,b)=>a-b);const playerSlot=num(player.player_slot);
  const parsedEvents=objectives.map((entry):MatchObjectiveEvent=>{const second=eventTime(entry),name=`${str(entry.type)||""} ${str(entry.key)||""}`.trim().toLowerCase(),previousKills=teamKills.filter((kill)=>kill<=second&&kill>=second-120),lastKill=previousKills.at(-1)??null,slot=num(entry.player_slot)??num(entry.slot),nearPlayerEvent=events.some((event)=>Math.abs(event.second-second)<=90&&(event.type==="kill"||event.type==="death"));return{type:objectiveKind(name),minute:Math.floor(second/60),label:name.replaceAll("_"," ")||"Objective",playerPresent:slot===playerSlot||nearPlayerEvent?true:null,delayAfterFightSeconds:lastKill===null?null:Math.round(second-lastKill),convertedFromFight:previousKills.length>=2?true:previousKills.length?null:false};});
  const fightWindows=teamKills.filter((second,index)=>index===0||second-teamKills[index-1]>75).map((start)=>({start,kills:teamKills.filter((value)=>value>=start&&value<=start+75)})).filter((fight)=>fight.kills.length>=2),conversionCount=parsedEvents.filter((event)=>event.convertedFromFight===true).length,missed=fightWindows.filter((fight)=>!objectives.some((entry)=>eventTime(entry)>=fight.start&&eventTime(entry)<=fight.start+195)).length,delays=parsedEvents.flatMap((event)=>event.delayAfterFightSeconds===null?[]:[event.delayAfterFightSeconds]),names=parsedEvents.map((entry)=>entry.type);
  return{availability:objectives.length||num(player.tower_damage)!==null?"partial" as const:"unavailable" as const,towerDamage:num(player.tower_damage),roshanKills:objectives.length?names.filter((name)=>name==="roshan").length:null,towerKills:objectives.length?names.filter((name)=>name==="tower").length:null,barracksKills:objectives.length?names.filter((name)=>name==="barracks").length:null,conversionCount:objectives.length?conversionCount:null,missedConversionCount:fightWindows.length?missed:null,averageConversionDelaySeconds:delays.length?Math.round(delays.reduce((sum,value)=>sum+value,0)/delays.length):null,events:parsedEvents,note:objectives.length?"Fight → Objective در پنجره ۱۲۰ ثانیه‌ای سنجیده شده؛ Presence فقط هنگام وجود Telemetry معتبر قطعی است.":"Objective log کامل برای این Match در دسترس نیست."};
}

function rawPosition(player:Raw){const position=num(player.position_est);if(position&&position>=1&&position<=5)return Math.round(position);const lane=num(player.lane_role);return lane&&lane>=1&&lane<=3?Math.round(lane):null;}
function invisThreats(allPlayers:Raw[],team:DotaTeam){return allPlayers.filter((entry)=>teamOf(entry)!==team).flatMap((entry)=>{const heroId=num(entry.hero_id),heroName=heroId===null?"Unknown":heroById(heroId)?.name??`Hero ${heroId}`,position=rawPosition(entry),result:Array<{label:string;second:number;active:boolean;position:number|null}>=[];if(heroId!==null&&INVIS_HEROES.has(heroId))result.push({label:`${heroName} · Ability Invis`,second:(levelSixMinute(entry)??6)*60,active:true,position});const complete=firstPurchaseSecond(entry,"glimmer_cape","shadow_blade","silver_edge");if(complete!==null)result.push({label:`${heroName} · Invis Item`,second:complete,active:true,position});const purchases=purchaseEntries(entry),amulet=purchases.find((item)=>item.key==="shadow_amulet"),secondary=purchases.find((item)=>item.key==="cloak"||item.key==="blitz_knuckles");if(amulet&&complete===null)result.push({label:`${heroName} · Invis build intent${secondary?" (high confidence)":""}`,second:Math.max(amulet.second,secondary?.second??amulet.second),active:false,position});return result;});}
function detectionResponsibility(position:number|null,threats:Array<{position:number|null;second:number}>,naturalReveal:boolean){if(position===null)return null;const early=threats.filter((threat)=>threat.second<600),against=early.length?early:threats;let score=position===4||position===5?88:position===3?62:42;for(const threat of against){if(threat.position===1&&(position===3||position===4))score=Math.max(score,94);if((threat.position===3||threat.position===4)&&(position===1||position===5))score=Math.max(score,90);if(threat.position===2&&(position===2||position===4))score=Math.max(score,88);}return Math.max(20,score-(naturalReveal?15:0));}
function utilityAnalysis(player:Raw,allPlayers:Raw[],rawMatch:Raw,team:DotaTeam,position:number|null){
  const observers=num(player.obs_placed)??countPurchase(player,"ward_observer"),sentries=num(player.sen_placed)??countPurchase(player,"ward_sentry"),dust=countPurchase(player,"dust"),gem=countPurchase(player,"gem"),smoke=countPurchase(player,"smoke_of_deceit"),lives=wardLives(player),average=lives.length?Math.round(lives.reduce((sum,value)=>sum+value.seconds,0)/lives.length):null,early=lives.length?lives.filter((value)=>value.seconds<120).length:null,objectiveTimes=records(rawMatch.objectives).map(eventTime),covered=lives.filter((ward)=>objectiveTimes.some((second)=>second>=ward.start&&second<=ward.end+90)).length,objectiveWardCoverage=lives.length&&objectiveTimes.length?percentage(covered,lives.length):null;
  const teamPlayers=allPlayers.filter((entry)=>teamOf(entry)===team),enemyPlayers=allPlayers.filter((entry)=>teamOf(entry)!==team),threats=invisThreats(allPlayers,team),firstThreat=threats.length?Math.floor(Math.min(...threats.map((entry)=>entry.second))/60):null,ownFirst=firstPurchaseSecond(player,"dust","ward_sentry","gem"),teamFirsts=teamPlayers.flatMap((entry)=>{const value=firstPurchaseSecond(entry,"dust","ward_sentry","gem");return value===null?[]:[value];}),teamFirst=teamFirsts.length?Math.min(...teamFirsts):null;
  const ownDetection=dust+sentries+gem,teamDetection=teamPlayers.reduce((sum,entry)=>sum+countPurchase(entry,"dust","ward_sentry","gem"),0),natural=teamPlayers.flatMap((entry)=>{const id=num(entry.hero_id);return id!==null&&NATURAL_REVEAL.has(id)?[NATURAL_REVEAL.get(id)!]:[];}),threatSecond=firstThreat===null?null:firstThreat*60,gap=threatSecond===null?null:teamFirst===null?null:Math.max(0,Math.round((teamFirst-threatSecond)/60)),prepared=threatSecond===null?null:teamFirst!==null&&teamFirst<=threatSecond;
  const teamKillTimes=teamPlayers.flatMap((entry)=>records(entry.kills_log).map(eventTime)),smokeTimes=purchaseEntries(player).filter((entry)=>entry.key==="smoke_of_deceit").map((entry)=>entry.second),successfulSmokes=smokeTimes.filter((second)=>teamKillTimes.some((kill)=>kill>=second&&kill<=second+120)||objectiveTimes.some((objective)=>objective>=second&&objective<=second+180)).length,lifetimeScore=average===null?0:Math.min(40,average/360*40),dewardScore=Math.min(25,(num(player.observer_kills)??0)*10+(num(player.sentry_kills)??0)*6),coverageScore=(objectiveWardCoverage??0)*.35,visionValue=observers+sentries?Math.round(Math.min(100,lifetimeScore+dewardScore+coverageScore)):null,responsibility=detectionResponsibility(position,threats,natural.length>0),timeliness=threatSecond===null?null:teamFirst===null?0:Math.max(0,100-Math.max(0,teamFirst-threatSecond)/6),teamDetectionScore=threats.length?Math.round(Math.min(100,(timeliness??0)*.7+Math.min(30,teamDetection*6)+(natural.length?8:0))):null,coreMultiplier=position&&position<=3?1.35:1,individualContribution=teamDetection?Math.min(100,Math.round(ownDetection/teamDetection*100*coreMultiplier)):null;
  return{availability:observers+sentries+dust+smoke+gem||threats.length?"partial" as const:"unavailable" as const,observersPlaced:observers,sentriesPlaced:sentries,observersDestroyed:num(player.observer_kills),sentriesDestroyed:num(player.sentry_kills),averageObserverLifetimeSeconds:average,observersDewardedEarly:early,visionValue,objectiveWardCoverage,campsStacked:num(player.camps_stacked)??num(player.creeps_stacked),smokeUses:smoke,successfulSmokes,dustUses:dust,gemPurchases:gem,invisThreat:threats.some((entry)=>entry.active)?"active" as const:threats.length?"possible" as const:"none" as const,invisThreats:[...new Set(threats.map((entry)=>entry.label))],naturalReveal:[...new Set(natural)],firstThreatMinute:firstThreat,firstDetectionMinute:ownFirst===null?null:Math.floor(ownFirst/60),preparedBeforeThreat:prepared,coverageGapMinutes:gap,teamDetectionScore,individualContribution,responsibilityScore:responsibility,note:threats.length?`${enemyPlayers.length} حریف بررسی شد؛ زمان تهدید، آمادگی تیم، Natural Reveal و مسئولیت Position جداگانه وزن گرفته‌اند.`:"Ability یا Item Invis قطعی/محتمل در تیم حریف ثبت نشد."};
}

export function buildPlayerMapAnalysis({player,allPlayers,rawMatch,timeline,events,team,position}:{player:Raw;allPlayers:Raw[];rawMatch:Raw;timeline:MatchMinuteSnapshot[];events:MatchAnalysisEvent[];team:DotaTeam;position:number|null}):MatchMapAnalysis{
  const timed=events.flatMap((event):MatchMapPoint[]=>event.x===null||event.x===undefined||event.y===null||event.y===undefined?[]:[{x:coord(event.x),y:100-coord(event.y),minute:event.minute,weight:1,type:event.type==="ward"||event.type==="sentry"?"vision":event.type==="kill"||event.type==="death"?"combat":"objective",label:event.label}]),aggregate=lanePoints(player,"movement"),points=[...aggregate,...timed],trail=timed.filter((point)=>point.minute!==null&&point.type==="combat").sort((a,b)=>(a.minute??0)-(b.minute??0));
  const lane=num(player.lane_kills),neutral=num(player.neutral_kills),ancient=num(player.ancient_kills),stacked=num(player.camps_stacked)??num(player.creeps_stacked),tracked=timeline.filter((point)=>point.lastHitDelta!==null).length,active=timeline.filter((point)=>(point.lastHitDelta??0)>0).length,total=(lane??0)+(neutral??0)+(ancient??0),farmKnown=[lane,neutral,ancient,stacked].some((value)=>value!==null)||tracked>1,combatMinutes=new Set(events.filter((event)=>event.type==="kill"||event.type==="death").map((event)=>event.minute)),empty=timeline.filter((point)=>point.minute>=10&&(point.lastHitDelta??0)<=0&&!combatMinutes.has(point.minute)&&(point.state==="steady"||point.state==="setback")).length,deadSeconds=num(player.life_state_dead),deathCost=deadSeconds===null||num(player.gold_per_min)===null?null:Math.round(deadSeconds/60*(num(player.gold_per_min) as number)),netWorth=num(player.net_worth),damage=num(player.hero_damage),farmToImpact=netWorth&&damage!==null?Math.round(Math.min(100,damage/netWorth*40)):null;
  const farm={availability:farmKnown?"partial" as const:"unavailable" as const,laneCreeps:lane,neutralCreeps:neutral,ancientCreeps:ancient,stackedCamps:stacked,farmUptimePercent:tracked>1?Math.round(active/tracked*100):null,recoveryRate:recovery(timeline),deathCost,emptyTravelMinutes:tracked>1?empty:null,farmToImpact,sourceMix:{lane:percentage(lane??0,total),neutral:percentage(neutral??0,total),ancient:percentage(ancient??0,total)},windows:farmWindows(timeline,events,Math.max(1,timeline.at(-1)?.minute??1)),note:farmKnown?"Farm Source، ریتم بازه‌ای، زمان بدون Farm، Death Cost و تبدیل Economy به Impact از Telemetry موجود استخراج شده‌اند.":"Replay این Match جزئیات کافی برای Farm Quality ندارد."},objectives=objectiveAnalysis(rawMatch,player,allPlayers,team,events),utility=utilityAnalysis(player,allPlayers,rawMatch,team,position);
  const timedMovement=trail,movementPoints=aggregate.length?aggregate:timedMovement,totalMovementWeight=movementPoints.reduce((sum,point)=>sum+Math.max(1,point.weight),0),territory=(point:MatchMapPoint)=>team==="radiant"?(100-point.x+point.y)/2:(point.x+100-point.y)/2,safeWeight=movementPoints.filter((point)=>territory(point)>=60).reduce((sum,point)=>sum+Math.max(1,point.weight),0),enemyWeight=movementPoints.filter((point)=>territory(point)<=40).reduce((sum,point)=>sum+Math.max(1,point.weight),0),movement={availability:movementPoints.length?"partial" as const:"unavailable" as const,safeTerritoryPercent:totalMovementWeight?percentage(safeWeight,totalMovementWeight):null,enemyTerritoryPercent:totalMovementWeight?percentage(enemyWeight,totalMovementWeight):null,combatPoints:timedMovement.length,objectivePoints:timed.filter((point)=>point.type==="objective").length,timedTrailPoints:timedMovement.length,note:aggregate.length?"Safe/Enemy territory از پوشش تجمعی محاسبه شده؛ برای ترتیب دقیق حرکت به Timed coordinates نیاز است.":timedMovement.length?"Territory share و Trail از نقاط Combat زمان‌دار موجود ساخته شده‌اند.":"مختصات قابل اتکا برای Movement ثبت نشده است."};
  return{availability:points.length||farmKnown||objectives.availability!=="unavailable"||utility.availability!=="unavailable"?"partial":"unavailable",coordinateSource:timed.length?"timed":aggregate.length?"aggregate":"unavailable",points,trail,farm,objectives,utility,movement};
}
