// Generated by scripts/sync-item-icons.mjs. Do not edit manually.

export interface DotaItem {
  id: number;
  slug: string;
  name: string;
}

export const DOTA_ITEMS = [
  {
    "id": 1,
    "slug": "blink",
    "name": "Blink Dagger"
  },
  {
    "id": 2,
    "slug": "blades_of_attack",
    "name": "Blades of Attack"
  },
  {
    "id": 3,
    "slug": "broadsword",
    "name": "Broadsword"
  },
  {
    "id": 4,
    "slug": "chainmail",
    "name": "Chainmail"
  },
  {
    "id": 5,
    "slug": "claymore",
    "name": "Claymore"
  },
  {
    "id": 6,
    "slug": "helm_of_iron_will",
    "name": "Helm of Iron Will"
  },
  {
    "id": 7,
    "slug": "javelin",
    "name": "Javelin"
  },
  {
    "id": 8,
    "slug": "mithril_hammer",
    "name": "Mithril Hammer"
  },
  {
    "id": 9,
    "slug": "platemail",
    "name": "Platemail"
  },
  {
    "id": 10,
    "slug": "quarterstaff",
    "name": "Quarterstaff"
  },
  {
    "id": 11,
    "slug": "quelling_blade",
    "name": "Quelling Blade"
  },
  {
    "id": 12,
    "slug": "ring_of_protection",
    "name": "Ring of Protection"
  },
  {
    "id": 13,
    "slug": "gauntlets",
    "name": "Gauntlets of Strength"
  },
  {
    "id": 14,
    "slug": "slippers",
    "name": "Slippers of Agility"
  },
  {
    "id": 15,
    "slug": "mantle",
    "name": "Mantle of Intelligence"
  },
  {
    "id": 16,
    "slug": "branches",
    "name": "Iron Branch"
  },
  {
    "id": 17,
    "slug": "belt_of_strength",
    "name": "Belt of Strength"
  },
  {
    "id": 18,
    "slug": "boots_of_elves",
    "name": "Band of Elvenskin"
  },
  {
    "id": 19,
    "slug": "robe",
    "name": "Robe of the Magi"
  },
  {
    "id": 20,
    "slug": "circlet",
    "name": "Circlet"
  },
  {
    "id": 21,
    "slug": "ogre_axe",
    "name": "Ogre Axe"
  },
  {
    "id": 22,
    "slug": "blade_of_alacrity",
    "name": "Blade of Alacrity"
  },
  {
    "id": 23,
    "slug": "staff_of_wizardry",
    "name": "Staff of Wizardry"
  },
  {
    "id": 24,
    "slug": "ultimate_orb",
    "name": "Ultimate Orb"
  },
  {
    "id": 25,
    "slug": "gloves",
    "name": "Gloves of Haste"
  },
  {
    "id": 26,
    "slug": "lifesteal",
    "name": "Morbid Mask"
  },
  {
    "id": 27,
    "slug": "ring_of_regen",
    "name": "Ring of Regen"
  },
  {
    "id": 28,
    "slug": "sobi_mask",
    "name": "Sage's Mask"
  },
  {
    "id": 29,
    "slug": "boots",
    "name": "Boots of Speed"
  },
  {
    "id": 30,
    "slug": "gem",
    "name": "Gem of True Sight"
  },
  {
    "id": 31,
    "slug": "cloak",
    "name": "Cloak"
  },
  {
    "id": 32,
    "slug": "talisman_of_evasion",
    "name": "Talisman of Evasion"
  },
  {
    "id": 33,
    "slug": "cheese",
    "name": "Cheese"
  },
  {
    "id": 34,
    "slug": "magic_stick",
    "name": "Magic Stick"
  },
  {
    "id": 35,
    "slug": "recipe",
    "name": "Magic Wand Recipe"
  },
  {
    "id": 36,
    "slug": "magic_wand",
    "name": "Magic Wand"
  },
  {
    "id": 37,
    "slug": "ghost",
    "name": "Ghost Scepter"
  },
  {
    "id": 38,
    "slug": "clarity",
    "name": "Clarity"
  },
  {
    "id": 39,
    "slug": "flask",
    "name": "Healing Salve"
  },
  {
    "id": 40,
    "slug": "dust",
    "name": "Dust of Appearance"
  },
  {
    "id": 41,
    "slug": "bottle",
    "name": "Bottle"
  },
  {
    "id": 42,
    "slug": "ward_observer",
    "name": "Observer Ward"
  },
  {
    "id": 43,
    "slug": "ward_sentry",
    "name": "Sentry Ward"
  },
  {
    "id": 44,
    "slug": "tango",
    "name": "Tango"
  },
  {
    "id": 45,
    "slug": "courier",
    "name": "Animal Courier"
  },
  {
    "id": 46,
    "slug": "tpscroll",
    "name": "Town Portal Scroll"
  },
  {
    "id": 47,
    "slug": "recipe",
    "name": "Boots of Travel Recipe"
  },
  {
    "id": 48,
    "slug": "travel_boots",
    "name": "Boots of Travel"
  },
  {
    "id": 50,
    "slug": "phase_boots",
    "name": "Phase Boots"
  },
  {
    "id": 51,
    "slug": "demon_edge",
    "name": "Demon Edge"
  },
  {
    "id": 52,
    "slug": "eagle",
    "name": "Eaglesong"
  },
  {
    "id": 53,
    "slug": "reaver",
    "name": "Reaver"
  },
  {
    "id": 54,
    "slug": "relic",
    "name": "Sacred Relic"
  },
  {
    "id": 55,
    "slug": "hyperstone",
    "name": "Hyperstone"
  },
  {
    "id": 56,
    "slug": "ring_of_health",
    "name": "Ring of Health"
  },
  {
    "id": 57,
    "slug": "void_stone",
    "name": "Void Stone"
  },
  {
    "id": 58,
    "slug": "mystic_staff",
    "name": "Mystic Staff"
  },
  {
    "id": 59,
    "slug": "energy_booster",
    "name": "Energy Booster"
  },
  {
    "id": 60,
    "slug": "point_booster",
    "name": "Point Booster"
  },
  {
    "id": 61,
    "slug": "vitality_booster",
    "name": "Vitality Booster"
  },
  {
    "id": 63,
    "slug": "power_treads",
    "name": "Power Treads"
  },
  {
    "id": 64,
    "slug": "recipe",
    "name": "Hand of Midas Recipe"
  },
  {
    "id": 65,
    "slug": "hand_of_midas",
    "name": "Hand of Midas"
  },
  {
    "id": 67,
    "slug": "oblivion_staff",
    "name": "Oblivion Staff"
  },
  {
    "id": 69,
    "slug": "pers",
    "name": "Perseverance"
  },
  {
    "id": 71,
    "slug": "poor_mans_shield",
    "name": "Poor Man's Shield"
  },
  {
    "id": 72,
    "slug": "recipe",
    "name": "Bracer Recipe"
  },
  {
    "id": 73,
    "slug": "bracer",
    "name": "Bracer"
  },
  {
    "id": 74,
    "slug": "recipe",
    "name": "Wraith Band Recipe"
  },
  {
    "id": 75,
    "slug": "wraith_band",
    "name": "Wraith Band"
  },
  {
    "id": 76,
    "slug": "recipe",
    "name": "Null Talisman Recipe"
  },
  {
    "id": 77,
    "slug": "null_talisman",
    "name": "Null Talisman"
  },
  {
    "id": 78,
    "slug": "recipe",
    "name": "Mekansm Recipe"
  },
  {
    "id": 79,
    "slug": "mekansm",
    "name": "Mekansm"
  },
  {
    "id": 81,
    "slug": "vladmir",
    "name": "Vladmir's Offering"
  },
  {
    "id": 85,
    "slug": "recipe",
    "name": "Buckler Recipe"
  },
  {
    "id": 86,
    "slug": "buckler",
    "name": "Buckler"
  },
  {
    "id": 87,
    "slug": "recipe",
    "name": "Ring of Basilius Recipe"
  },
  {
    "id": 88,
    "slug": "ring_of_basilius",
    "name": "Ring of Basilius"
  },
  {
    "id": 89,
    "slug": "recipe",
    "name": "Pipe of Insight Recipe"
  },
  {
    "id": 90,
    "slug": "pipe",
    "name": "Pipe of Insight"
  },
  {
    "id": 91,
    "slug": "recipe",
    "name": "Urn of Shadows Recipe"
  },
  {
    "id": 92,
    "slug": "urn_of_shadows",
    "name": "Urn of Shadows"
  },
  {
    "id": 93,
    "slug": "recipe",
    "name": "Headdress Recipe"
  },
  {
    "id": 94,
    "slug": "headdress",
    "name": "Headdress"
  },
  {
    "id": 95,
    "slug": "recipe",
    "name": "Scythe of Vyse Recipe"
  },
  {
    "id": 96,
    "slug": "sheepstick",
    "name": "Scythe of Vyse"
  },
  {
    "id": 97,
    "slug": "recipe",
    "name": "Orchid Malevolence Recipe"
  },
  {
    "id": 98,
    "slug": "orchid",
    "name": "Orchid Malevolence"
  },
  {
    "id": 99,
    "slug": "recipe",
    "name": "Eul's Scepter Recipe"
  },
  {
    "id": 100,
    "slug": "cyclone",
    "name": "Eul's Scepter of Divinity"
  },
  {
    "id": 101,
    "slug": "recipe",
    "name": "Force Staff Recipe"
  },
  {
    "id": 102,
    "slug": "force_staff",
    "name": "Force Staff"
  },
  {
    "id": 103,
    "slug": "recipe",
    "name": "Dagon Recipe"
  },
  {
    "id": 104,
    "slug": "dagon",
    "name": "Dagon"
  },
  {
    "id": 105,
    "slug": "recipe",
    "name": "Necronomicon Recipe"
  },
  {
    "id": 106,
    "slug": "necronomicon",
    "name": "Necronomicon"
  },
  {
    "id": 108,
    "slug": "ultimate_scepter",
    "name": "Aghanim's Scepter"
  },
  {
    "id": 109,
    "slug": "recipe",
    "name": "Refresher Orb Recipe"
  },
  {
    "id": 110,
    "slug": "refresher",
    "name": "Refresher Orb"
  },
  {
    "id": 111,
    "slug": "recipe",
    "name": "Assault Cuirass Recipe"
  },
  {
    "id": 112,
    "slug": "assault",
    "name": "Assault Cuirass"
  },
  {
    "id": 113,
    "slug": "recipe",
    "name": "Heart of Tarrasque Recipe"
  },
  {
    "id": 114,
    "slug": "heart",
    "name": "Heart of Tarrasque"
  },
  {
    "id": 115,
    "slug": "recipe",
    "name": "Black King Bar Recipe"
  },
  {
    "id": 116,
    "slug": "black_king_bar",
    "name": "Black King Bar"
  },
  {
    "id": 117,
    "slug": "aegis",
    "name": "Aegis of the Immortal"
  },
  {
    "id": 118,
    "slug": "recipe",
    "name": "Shiva's Guard Recipe"
  },
  {
    "id": 119,
    "slug": "shivas_guard",
    "name": "Shiva's Guard"
  },
  {
    "id": 121,
    "slug": "bloodstone",
    "name": "Bloodstone"
  },
  {
    "id": 122,
    "slug": "recipe",
    "name": "Linken's Sphere Recipe"
  },
  {
    "id": 123,
    "slug": "sphere",
    "name": "Linken's Sphere"
  },
  {
    "id": 125,
    "slug": "vanguard",
    "name": "Vanguard"
  },
  {
    "id": 126,
    "slug": "recipe",
    "name": "Blade Mail Recipe"
  },
  {
    "id": 127,
    "slug": "blade_mail",
    "name": "Blade Mail"
  },
  {
    "id": 129,
    "slug": "soul_booster",
    "name": "Soul Booster"
  },
  {
    "id": 131,
    "slug": "hood_of_defiance",
    "name": "Hood of Defiance"
  },
  {
    "id": 133,
    "slug": "rapier",
    "name": "Divine Rapier"
  },
  {
    "id": 134,
    "slug": "recipe",
    "name": "Monkey King Bar Recipe"
  },
  {
    "id": 135,
    "slug": "monkey_king_bar",
    "name": "Monkey King Bar"
  },
  {
    "id": 137,
    "slug": "radiance",
    "name": "Radiance"
  },
  {
    "id": 139,
    "slug": "butterfly",
    "name": "Butterfly"
  },
  {
    "id": 140,
    "slug": "recipe",
    "name": "Daedalus Recipe"
  },
  {
    "id": 141,
    "slug": "greater_crit",
    "name": "Daedalus"
  },
  {
    "id": 142,
    "slug": "recipe",
    "name": "Skull Basher Recipe"
  },
  {
    "id": 143,
    "slug": "basher",
    "name": "Skull Basher"
  },
  {
    "id": 144,
    "slug": "recipe",
    "name": "Battle Fury Recipe"
  },
  {
    "id": 145,
    "slug": "bfury",
    "name": "Battle Fury"
  },
  {
    "id": 146,
    "slug": "recipe",
    "name": "Manta Style Recipe"
  },
  {
    "id": 147,
    "slug": "manta",
    "name": "Manta Style"
  },
  {
    "id": 148,
    "slug": "recipe",
    "name": "Crystalys Recipe"
  },
  {
    "id": 149,
    "slug": "lesser_crit",
    "name": "Crystalys"
  },
  {
    "id": 150,
    "slug": "recipe",
    "name": "Armlet of Mordiggian Recipe"
  },
  {
    "id": 151,
    "slug": "armlet",
    "name": "Armlet of Mordiggian"
  },
  {
    "id": 152,
    "slug": "invis_sword",
    "name": "Shadow Blade"
  },
  {
    "id": 154,
    "slug": "sange_and_yasha",
    "name": "Sange and Yasha"
  },
  {
    "id": 156,
    "slug": "satanic",
    "name": "Satanic"
  },
  {
    "id": 157,
    "slug": "recipe",
    "name": "Mjollnir Recipe"
  },
  {
    "id": 158,
    "slug": "mjollnir",
    "name": "Mjollnir"
  },
  {
    "id": 160,
    "slug": "skadi",
    "name": "Eye of Skadi"
  },
  {
    "id": 161,
    "slug": "recipe",
    "name": "Sange Recipe"
  },
  {
    "id": 162,
    "slug": "sange",
    "name": "Sange"
  },
  {
    "id": 163,
    "slug": "recipe",
    "name": "Helm of the Dominator Recipe"
  },
  {
    "id": 164,
    "slug": "helm_of_the_dominator",
    "name": "Helm of the Dominator"
  },
  {
    "id": 166,
    "slug": "maelstrom",
    "name": "Maelstrom"
  },
  {
    "id": 168,
    "slug": "desolator",
    "name": "Desolator"
  },
  {
    "id": 169,
    "slug": "recipe",
    "name": "Yasha Recipe"
  },
  {
    "id": 170,
    "slug": "yasha",
    "name": "Yasha"
  },
  {
    "id": 172,
    "slug": "mask_of_madness",
    "name": "Mask of Madness"
  },
  {
    "id": 173,
    "slug": "recipe",
    "name": "Diffusal Blade Recipe"
  },
  {
    "id": 174,
    "slug": "diffusal_blade",
    "name": "Diffusal Blade"
  },
  {
    "id": 175,
    "slug": "recipe",
    "name": "Ethereal Blade Recipe"
  },
  {
    "id": 176,
    "slug": "ethereal_blade",
    "name": "Ethereal Blade"
  },
  {
    "id": 177,
    "slug": "recipe",
    "name": "Soul Ring Recipe"
  },
  {
    "id": 178,
    "slug": "soul_ring",
    "name": "Soul Ring"
  },
  {
    "id": 179,
    "slug": "recipe",
    "name": "Arcane Boots Recipe"
  },
  {
    "id": 180,
    "slug": "arcane_boots",
    "name": "Arcane Boots"
  },
  {
    "id": 181,
    "slug": "orb_of_venom",
    "name": "Orb of Venom"
  },
  {
    "id": 182,
    "slug": "stout_shield",
    "name": "Stout Shield"
  },
  {
    "id": 184,
    "slug": "recipe",
    "name": "Drum of Endurance Recipe"
  },
  {
    "id": 185,
    "slug": "ancient_janggo",
    "name": "Drum of Endurance"
  },
  {
    "id": 187,
    "slug": "medallion_of_courage",
    "name": "Medallion of Courage"
  },
  {
    "id": 188,
    "slug": "smoke_of_deceit",
    "name": "Smoke of Deceit"
  },
  {
    "id": 189,
    "slug": "recipe",
    "name": "Veil of Discord Recipe"
  },
  {
    "id": 190,
    "slug": "veil_of_discord",
    "name": "Veil of Discord"
  },
  {
    "id": 193,
    "slug": "necronomicon_2",
    "name": "Necronomicon"
  },
  {
    "id": 194,
    "slug": "necronomicon_3",
    "name": "Necronomicon"
  },
  {
    "id": 196,
    "slug": "diffusal_blade_2",
    "name": "Diffusal Blade"
  },
  {
    "id": 201,
    "slug": "dagon_2",
    "name": "Dagon"
  },
  {
    "id": 202,
    "slug": "dagon_3",
    "name": "Dagon"
  },
  {
    "id": 203,
    "slug": "dagon_4",
    "name": "Dagon"
  },
  {
    "id": 204,
    "slug": "dagon_5",
    "name": "Dagon"
  },
  {
    "id": 205,
    "slug": "recipe",
    "name": "Rod of Atos Recipe"
  },
  {
    "id": 206,
    "slug": "rod_of_atos",
    "name": "Rod of Atos"
  },
  {
    "id": 207,
    "slug": "recipe",
    "name": "Abyssal Blade Recipe"
  },
  {
    "id": 208,
    "slug": "abyssal_blade",
    "name": "Abyssal Blade"
  },
  {
    "id": 209,
    "slug": "recipe",
    "name": "Heaven's Halberd Recipe"
  },
  {
    "id": 210,
    "slug": "heavens_halberd",
    "name": "Heaven's Halberd"
  },
  {
    "id": 212,
    "slug": "ring_of_aquila",
    "name": "Ring of Aquila"
  },
  {
    "id": 214,
    "slug": "tranquil_boots",
    "name": "Tranquil Boots"
  },
  {
    "id": 215,
    "slug": "shadow_amulet",
    "name": "Shadow Amulet"
  },
  {
    "id": 216,
    "slug": "enchanted_mango",
    "name": "Enchanted Mango"
  },
  {
    "id": 218,
    "slug": "ward_dispenser",
    "name": "Observer and Sentry Wards"
  },
  {
    "id": 220,
    "slug": "travel_boots_2",
    "name": "Boots of Travel 2"
  },
  {
    "id": 221,
    "slug": "recipe",
    "name": "Lotus Orb Recipe"
  },
  {
    "id": 222,
    "slug": "recipe",
    "name": "Meteor Hammer Recipe"
  },
  {
    "id": 223,
    "slug": "meteor_hammer",
    "name": "Meteor Hammer"
  },
  {
    "id": 225,
    "slug": "nullifier",
    "name": "Nullifier"
  },
  {
    "id": 226,
    "slug": "lotus_orb",
    "name": "Lotus Orb"
  },
  {
    "id": 227,
    "slug": "recipe",
    "name": "Solar Crest Recipe"
  },
  {
    "id": 228,
    "slug": "recipe",
    "name": "Octarine Core Recipe"
  },
  {
    "id": 229,
    "slug": "solar_crest",
    "name": "Solar Crest"
  },
  {
    "id": 230,
    "slug": "recipe",
    "name": "Guardian Greaves Recipe"
  },
  {
    "id": 231,
    "slug": "guardian_greaves",
    "name": "Guardian Greaves"
  },
  {
    "id": 232,
    "slug": "aether_lens",
    "name": "Aether Lens"
  },
  {
    "id": 233,
    "slug": "recipe",
    "name": "Aether Lens Recipe"
  },
  {
    "id": 234,
    "slug": "recipe",
    "name": "Dragon Lance Recipe"
  },
  {
    "id": 235,
    "slug": "octarine_core",
    "name": "Octarine Core"
  },
  {
    "id": 236,
    "slug": "dragon_lance",
    "name": "Dragon Lance"
  },
  {
    "id": 237,
    "slug": "faerie_fire",
    "name": "Faerie Fire"
  },
  {
    "id": 238,
    "slug": "recipe",
    "name": "Iron Talon Recipe"
  },
  {
    "id": 239,
    "slug": "iron_talon",
    "name": "Iron Talon"
  },
  {
    "id": 240,
    "slug": "blight_stone",
    "name": "Orb of Blight"
  },
  {
    "id": 241,
    "slug": "tango_single",
    "name": "Tango (Shared)"
  },
  {
    "id": 242,
    "slug": "crimson_guard",
    "name": "Crimson Guard"
  },
  {
    "id": 243,
    "slug": "recipe",
    "name": "Crimson Guard Recipe"
  },
  {
    "id": 244,
    "slug": "wind_lace",
    "name": "Wind Lace"
  },
  {
    "id": 245,
    "slug": "recipe",
    "name": "Bloodthorn Recipe"
  },
  {
    "id": 247,
    "slug": "moon_shard",
    "name": "Moon Shard"
  },
  {
    "id": 248,
    "slug": "recipe",
    "name": "Silver Edge Recipe"
  },
  {
    "id": 249,
    "slug": "silver_edge",
    "name": "Silver Edge"
  },
  {
    "id": 250,
    "slug": "bloodthorn",
    "name": "Bloodthorn"
  },
  {
    "id": 252,
    "slug": "echo_sabre",
    "name": "Echo Sabre"
  },
  {
    "id": 253,
    "slug": "recipe",
    "name": "Glimmer Cape Recipe"
  },
  {
    "id": 254,
    "slug": "glimmer_cape",
    "name": "Glimmer Cape"
  },
  {
    "id": 255,
    "slug": "recipe",
    "name": "Aeon Disk Recipe"
  },
  {
    "id": 256,
    "slug": "aeon_disk",
    "name": "Aeon Disk"
  },
  {
    "id": 257,
    "slug": "tome_of_knowledge",
    "name": "Tome of Knowledge"
  },
  {
    "id": 258,
    "slug": "recipe",
    "name": "Kaya Recipe"
  },
  {
    "id": 259,
    "slug": "kaya",
    "name": "Kaya"
  },
  {
    "id": 260,
    "slug": "refresher_shard",
    "name": "Refresher Shard"
  },
  {
    "id": 261,
    "slug": "crown",
    "name": "Crown"
  },
  {
    "id": 262,
    "slug": "recipe",
    "name": "Hurricane Pike Recipe"
  },
  {
    "id": 263,
    "slug": "hurricane_pike",
    "name": "Hurricane Pike"
  },
  {
    "id": 265,
    "slug": "infused_raindrop",
    "name": "Infused Raindrops"
  },
  {
    "id": 266,
    "slug": "recipe",
    "name": "Spirit Vessel Recipe"
  },
  {
    "id": 267,
    "slug": "spirit_vessel",
    "name": "Spirit Vessel"
  },
  {
    "id": 268,
    "slug": "recipe",
    "name": "Holy Locket Recipe"
  },
  {
    "id": 269,
    "slug": "holy_locket",
    "name": "Holy Locket"
  },
  {
    "id": 270,
    "slug": "recipe",
    "name": "Aghanim's Blessing Recipe"
  },
  {
    "id": 271,
    "slug": "ultimate_scepter_2",
    "name": "Aghanim's Blessing"
  },
  {
    "id": 273,
    "slug": "kaya_and_sange",
    "name": "Kaya and Sange"
  },
  {
    "id": 275,
    "slug": "recipe",
    "name": "Trident Recipe"
  },
  {
    "id": 277,
    "slug": "yasha_and_kaya",
    "name": "Yasha and Kaya"
  },
  {
    "id": 279,
    "slug": "ring_of_tarrasque",
    "name": "Ring of Tarrasque"
  },
  {
    "id": 286,
    "slug": "flying_courier",
    "name": "Flying Courier"
  },
  {
    "id": 287,
    "slug": "keen_optic",
    "name": "Keen Optic"
  },
  {
    "id": 288,
    "slug": "grove_bow",
    "name": "Grove Bow"
  },
  {
    "id": 289,
    "slug": "quickening_charm",
    "name": "Quickening Charm"
  },
  {
    "id": 290,
    "slug": "philosophers_stone",
    "name": "Philosopher's Stone"
  },
  {
    "id": 291,
    "slug": "force_boots",
    "name": "Force Boots"
  },
  {
    "id": 292,
    "slug": "desolator_2",
    "name": "Stygian Desolator"
  },
  {
    "id": 293,
    "slug": "phoenix_ash",
    "name": "Phoenix Ash"
  },
  {
    "id": 294,
    "slug": "seer_stone",
    "name": "Seer Stone"
  },
  {
    "id": 295,
    "slug": "greater_mango",
    "name": "greater_mango"
  },
  {
    "id": 297,
    "slug": "vampire_fangs",
    "name": "Vampire Fangs"
  },
  {
    "id": 298,
    "slug": "craggy_coat",
    "name": "Craggy Coat"
  },
  {
    "id": 299,
    "slug": "greater_faerie_fire",
    "name": "Greater Faerie Fire"
  },
  {
    "id": 300,
    "slug": "timeless_relic",
    "name": "Timeless Relic"
  },
  {
    "id": 301,
    "slug": "mirror_shield",
    "name": "Mirror Shield"
  },
  {
    "id": 302,
    "slug": "elixer",
    "name": "Elixir"
  },
  {
    "id": 304,
    "slug": "ironwood_tree",
    "name": "Ironwood Tree"
  },
  {
    "id": 305,
    "slug": "royal_jelly",
    "name": "Royal Jelly"
  },
  {
    "id": 306,
    "slug": "pupils_gift",
    "name": "Pupil's Gift"
  },
  {
    "id": 307,
    "slug": "tome_of_aghanim",
    "name": "Tome of Aghanim"
  },
  {
    "id": 308,
    "slug": "repair_kit",
    "name": "Repair Kit"
  },
  {
    "id": 309,
    "slug": "mind_breaker",
    "name": "Mind Breaker"
  },
  {
    "id": 310,
    "slug": "third_eye",
    "name": "Third Eye"
  },
  {
    "id": 311,
    "slug": "spell_prism",
    "name": "Spell Prism"
  },
  {
    "id": 312,
    "slug": "horizon",
    "name": "horizon"
  },
  {
    "id": 313,
    "slug": "fusion_rune",
    "name": "Fusion Rune"
  },
  {
    "id": 325,
    "slug": "princes_knife",
    "name": "Prince's Knife"
  },
  {
    "id": 326,
    "slug": "spider_legs",
    "name": "Spider Legs"
  },
  {
    "id": 327,
    "slug": "helm_of_the_undying",
    "name": "Helm of the Undying"
  },
  {
    "id": 328,
    "slug": "mango_tree",
    "name": "Mango Tree"
  },
  {
    "id": 330,
    "slug": "witless_shako",
    "name": "Witless Shako"
  },
  {
    "id": 331,
    "slug": "vambrace",
    "name": "Vambrace"
  },
  {
    "id": 334,
    "slug": "imp_claw",
    "name": "Imp Claw"
  },
  {
    "id": 335,
    "slug": "flicker",
    "name": "Flicker"
  },
  {
    "id": 336,
    "slug": "spy_gadget",
    "name": "Telescope"
  },
  {
    "id": 349,
    "slug": "arcane_ring",
    "name": "Arcane Ring"
  },
  {
    "id": 354,
    "slug": "ocean_heart",
    "name": "Ocean Heart"
  },
  {
    "id": 355,
    "slug": "broom_handle",
    "name": "Broom Handle"
  },
  {
    "id": 356,
    "slug": "trusty_shovel",
    "name": "Trusty Shovel"
  },
  {
    "id": 357,
    "slug": "nether_shawl",
    "name": "Nether Shawl"
  },
  {
    "id": 358,
    "slug": "dragon_scale",
    "name": "Dragon Scale"
  },
  {
    "id": 359,
    "slug": "essence_ring",
    "name": "Essence Ring"
  },
  {
    "id": 360,
    "slug": "clumsy_net",
    "name": "Clumsy Net"
  },
  {
    "id": 361,
    "slug": "enchanted_quiver",
    "name": "Enchanted Quiver"
  },
  {
    "id": 362,
    "slug": "ninja_gear",
    "name": "Ninja Gear"
  },
  {
    "id": 363,
    "slug": "illusionsts_cape",
    "name": "Illusionist's Cape"
  },
  {
    "id": 364,
    "slug": "havoc_hammer",
    "name": "Havoc Hammer"
  },
  {
    "id": 365,
    "slug": "panic_button",
    "name": "Magic Lamp"
  },
  {
    "id": 366,
    "slug": "apex",
    "name": "Apex"
  },
  {
    "id": 367,
    "slug": "ballista",
    "name": "Ballista"
  },
  {
    "id": 368,
    "slug": "woodland_striders",
    "name": "Woodland Striders"
  },
  {
    "id": 369,
    "slug": "trident",
    "name": "Trident"
  },
  {
    "id": 370,
    "slug": "demonicon",
    "name": "Book of the Dead"
  },
  {
    "id": 371,
    "slug": "fallen_sky",
    "name": "Fallen Sky"
  },
  {
    "id": 372,
    "slug": "pirate_hat",
    "name": "Pirate Hat"
  },
  {
    "id": 374,
    "slug": "ex_machina",
    "name": "Ex Machina"
  },
  {
    "id": 375,
    "slug": "faded_broach",
    "name": "Faded Broach"
  },
  {
    "id": 376,
    "slug": "paladin_sword",
    "name": "Paladin Sword"
  },
  {
    "id": 377,
    "slug": "minotaur_horn",
    "name": "Minotaur Horn"
  },
  {
    "id": 378,
    "slug": "orb_of_destruction",
    "name": "Orb of Destruction"
  },
  {
    "id": 379,
    "slug": "the_leveller",
    "name": "The Leveller"
  },
  {
    "id": 381,
    "slug": "titan_sliver",
    "name": "Titan Sliver"
  },
  {
    "id": 473,
    "slug": "voodoo_mask",
    "name": "Voodoo Mask"
  },
  {
    "id": 485,
    "slug": "blitz_knuckles",
    "name": "Blitz Knuckles"
  },
  {
    "id": 533,
    "slug": "recipe",
    "name": "Witch Blade Recipe"
  },
  {
    "id": 534,
    "slug": "witch_blade",
    "name": "Witch Blade"
  },
  {
    "id": 565,
    "slug": "chipped_vest",
    "name": "Chipped Vest"
  },
  {
    "id": 569,
    "slug": "orb_of_corrosion",
    "name": "Orb of Corrosion"
  },
  {
    "id": 571,
    "slug": "trickster_cloak",
    "name": "Trickster Cloak"
  },
  {
    "id": 573,
    "slug": "elven_tunic",
    "name": "Elven Tunic"
  },
  {
    "id": 574,
    "slug": "cloak_of_flames",
    "name": "Cloak of Flames"
  },
  {
    "id": 577,
    "slug": "possessed_mask",
    "name": "Possessed Mask"
  },
  {
    "id": 585,
    "slug": "stormcrafter",
    "name": "Stormcrafter"
  },
  {
    "id": 589,
    "slug": "mysterious_hat",
    "name": "Fairy's Trinket"
  },
  {
    "id": 593,
    "slug": "fluffy_hat",
    "name": "Fluffy Hat"
  },
  {
    "id": 596,
    "slug": "falcon_blade",
    "name": "Falcon Blade"
  },
  {
    "id": 598,
    "slug": "mage_slayer",
    "name": "Mage Slayer"
  },
  {
    "id": 599,
    "slug": "recipe",
    "name": "Falcon Blade Recipe"
  },
  {
    "id": 600,
    "slug": "overwhelming_blink",
    "name": "Overwhelming Blink"
  },
  {
    "id": 603,
    "slug": "swift_blink",
    "name": "Swift Blink"
  },
  {
    "id": 604,
    "slug": "arcane_blink",
    "name": "Arcane Blink"
  },
  {
    "id": 606,
    "slug": "recipe",
    "name": "Arcane Blink Recipe"
  },
  {
    "id": 607,
    "slug": "recipe",
    "name": "Swift Blink Recipe"
  },
  {
    "id": 608,
    "slug": "recipe",
    "name": "Overwhelming Blink Recipe"
  },
  {
    "id": 609,
    "slug": "aghanims_shard",
    "name": "Aghanim's Shard"
  },
  {
    "id": 610,
    "slug": "wind_waker",
    "name": "Wind Waker"
  },
  {
    "id": 612,
    "slug": "recipe",
    "name": "Wind Waker Recipe"
  },
  {
    "id": 633,
    "slug": "recipe",
    "name": "Helm of the Overlord Recipe"
  },
  {
    "id": 635,
    "slug": "helm_of_the_overlord",
    "name": "Helm of the Overlord"
  },
  {
    "id": 638,
    "slug": "penta_edged_sword",
    "name": "Penta-Edged Sword"
  },
  {
    "id": 675,
    "slug": "psychic_headband",
    "name": "Psychic Headband"
  },
  {
    "id": 676,
    "slug": "ceremonial_robe",
    "name": "Ceremonial Robe"
  },
  {
    "id": 677,
    "slug": "book_of_shadows",
    "name": "Book of Shadows"
  },
  {
    "id": 678,
    "slug": "giants_ring",
    "name": "Giant's Ring"
  },
  {
    "id": 680,
    "slug": "bullwhip",
    "name": "Bullwhip"
  },
  {
    "id": 686,
    "slug": "quicksilver_amulet",
    "name": "Quicksilver Amulet"
  },
  {
    "id": 691,
    "slug": "recipe",
    "name": "Eternal Shroud Recipe"
  },
  {
    "id": 692,
    "slug": "eternal_shroud",
    "name": "Eternal Shroud"
  },
  {
    "id": 725,
    "slug": "aghanims_shard_roshan",
    "name": "Aghanim's Shard - Consumable"
  },
  {
    "id": 727,
    "slug": "ultimate_scepter_roshan",
    "name": "Aghanim's Blessing - Roshan"
  },
  {
    "id": 825,
    "slug": "ascetic_cap",
    "name": "Ascetic's Cap"
  },
  {
    "id": 828,
    "slug": "misericorde",
    "name": "Brigand's Blade"
  },
  {
    "id": 829,
    "slug": "force_field",
    "name": "Arcanist's Armor"
  },
  {
    "id": 834,
    "slug": "black_powder_bag",
    "name": "Blast Rig"
  },
  {
    "id": 835,
    "slug": "paintball",
    "name": "Fae Grenade"
  },
  {
    "id": 837,
    "slug": "heavy_blade",
    "name": "Witchbane"
  },
  {
    "id": 838,
    "slug": "unstable_wand",
    "name": "Pig Pole"
  },
  {
    "id": 840,
    "slug": "pogo_stick",
    "name": "Tumbler's Toy"
  },
  {
    "id": 849,
    "slug": "mechanical_arm",
    "name": "mechanical_arm"
  },
  {
    "id": 907,
    "slug": "recipe",
    "name": "recipe_wraith_pact"
  },
  {
    "id": 908,
    "slug": "wraith_pact",
    "name": "Wraith Pact"
  },
  {
    "id": 910,
    "slug": "recipe",
    "name": "Revenant's Brooch Recipe"
  },
  {
    "id": 911,
    "slug": "revenants_brooch",
    "name": "Revenant's Brooch"
  },
  {
    "id": 931,
    "slug": "boots_of_bearing",
    "name": "Boots of Bearing"
  },
  {
    "id": 939,
    "slug": "harpoon",
    "name": "Harpoon"
  },
  {
    "id": 945,
    "slug": "seeds_of_serenity",
    "name": "Seeds of Serenity"
  },
  {
    "id": 946,
    "slug": "lance_of_pursuit",
    "name": "Lance of Pursuit"
  },
  {
    "id": 947,
    "slug": "occult_bracelet",
    "name": "Occult Bracelet"
  },
  {
    "id": 949,
    "slug": "ogre_seal_totem",
    "name": "Ogre Seal Totem"
  },
  {
    "id": 950,
    "slug": "defiant_shell",
    "name": "Defiant Shell"
  },
  {
    "id": 990,
    "slug": "eye_of_the_vizier",
    "name": "Eye of the Vizier"
  },
  {
    "id": 1000,
    "slug": "bottomless_chalice",
    "name": "bottomless_chalice"
  },
  {
    "id": 1021,
    "slug": "river_painter",
    "name": "River Vial: Chrome"
  },
  {
    "id": 1022,
    "slug": "river_painter2",
    "name": "River Vial: Dry"
  },
  {
    "id": 1023,
    "slug": "river_painter3",
    "name": "River Vial: Slime"
  },
  {
    "id": 1024,
    "slug": "river_painter4",
    "name": "River Vial: Oil"
  },
  {
    "id": 1025,
    "slug": "river_painter5",
    "name": "River Vial: Electrified"
  },
  {
    "id": 1026,
    "slug": "river_painter6",
    "name": "River Vial: Potion"
  },
  {
    "id": 1027,
    "slug": "river_painter7",
    "name": "River Vial: Blood"
  },
  {
    "id": 1028,
    "slug": "mutation_tombstone",
    "name": "Tombstone"
  },
  {
    "id": 1029,
    "slug": "super_blink",
    "name": "super_blink"
  },
  {
    "id": 1030,
    "slug": "pocket_tower",
    "name": "Pocket Tower"
  },
  {
    "id": 1032,
    "slug": "pocket_roshan",
    "name": "Pocket Roshan"
  },
  {
    "id": 1076,
    "slug": "specialists_array",
    "name": "Specialist's Array"
  },
  {
    "id": 1077,
    "slug": "dagger_of_ristul",
    "name": "Dagger of Ristul"
  },
  {
    "id": 1090,
    "slug": "muertas_gun",
    "name": "Mercy & Grace"
  },
  {
    "id": 1096,
    "slug": "recipe",
    "name": "Disperser Recipe"
  },
  {
    "id": 1097,
    "slug": "disperser",
    "name": "Disperser"
  },
  {
    "id": 1101,
    "slug": "recipe",
    "name": "Harpoon Recipe"
  },
  {
    "id": 1106,
    "slug": "recipe",
    "name": "Phylactery Recipe"
  },
  {
    "id": 1107,
    "slug": "phylactery",
    "name": "Phylactery"
  },
  {
    "id": 1122,
    "slug": "diadem",
    "name": "Diadem"
  },
  {
    "id": 1123,
    "slug": "blood_grenade",
    "name": "Blood Grenade"
  },
  {
    "id": 1124,
    "slug": "spark_of_courage",
    "name": "Spark of Courage"
  },
  {
    "id": 1125,
    "slug": "cornucopia",
    "name": "Cornucopia"
  },
  {
    "id": 1127,
    "slug": "recipe",
    "name": "Pavise Recipe"
  },
  {
    "id": 1128,
    "slug": "pavise",
    "name": "Pavise"
  },
  {
    "id": 1154,
    "slug": "royale_with_cheese",
    "name": "Block of Cheese"
  },
  {
    "id": 1156,
    "slug": "ancient_guardian",
    "name": "Ancient Guardian"
  },
  {
    "id": 1157,
    "slug": "safety_bubble",
    "name": "Safety Bubble"
  },
  {
    "id": 1158,
    "slug": "whisper_of_the_dread",
    "name": "Whisper of the Dread"
  },
  {
    "id": 1159,
    "slug": "nemesis_curse",
    "name": "Nemesis Curse"
  },
  {
    "id": 1160,
    "slug": "avianas_feather",
    "name": "Aviana's Feather"
  },
  {
    "id": 1161,
    "slug": "unwavering_condition",
    "name": "Unwavering Condition"
  },
  {
    "id": 1167,
    "slug": "light_collector",
    "name": "Light Collector"
  },
  {
    "id": 1168,
    "slug": "rattlecage",
    "name": "Rattlecage"
  },
  {
    "id": 1440,
    "slug": "black_grimoire",
    "name": "Black Grimoire\\n(Warlock)"
  },
  {
    "id": 1441,
    "slug": "grisgris",
    "name": "Gris-Gris"
  },
  {
    "id": 1466,
    "slug": "gungir",
    "name": "Gleipnir"
  },
  {
    "id": 1565,
    "slug": "recipe",
    "name": "Gleipnir Recipe"
  },
  {
    "id": 1575,
    "slug": "orb_of_frost",
    "name": "Orb of Frost"
  },
  {
    "id": 1576,
    "slug": "enhancement_vast",
    "name": "Vast"
  },
  {
    "id": 1577,
    "slug": "enhancement_quickened",
    "name": "Quickened"
  },
  {
    "id": 1581,
    "slug": "enhancement_audacious",
    "name": "Audacious"
  },
  {
    "id": 1583,
    "slug": "enhancement_mystical",
    "name": "Mystical"
  },
  {
    "id": 1584,
    "slug": "enhancement_alert",
    "name": "Alert"
  },
  {
    "id": 1585,
    "slug": "enhancement_brawny",
    "name": "Brawny"
  },
  {
    "id": 1586,
    "slug": "enhancement_tough",
    "name": "Tough"
  },
  {
    "id": 1587,
    "slug": "enhancement_feverish",
    "name": "Feverish"
  },
  {
    "id": 1588,
    "slug": "enhancement_fleetfooted",
    "name": "Fleetfooted"
  },
  {
    "id": 1589,
    "slug": "enhancement_crude",
    "name": "Crude"
  },
  {
    "id": 1590,
    "slug": "enhancement_boundless",
    "name": "Boundless"
  },
  {
    "id": 1591,
    "slug": "enhancement_wise",
    "name": "Wise"
  },
  {
    "id": 1592,
    "slug": "enhancement_timeless",
    "name": "Timeless"
  },
  {
    "id": 1593,
    "slug": "enhancement_greedy",
    "name": "Greedy"
  },
  {
    "id": 1594,
    "slug": "enhancement_vampiric",
    "name": "Vampiric"
  },
  {
    "id": 1595,
    "slug": "enhancement_keen_eyed",
    "name": "Keen-eyed"
  },
  {
    "id": 1596,
    "slug": "enhancement_evolved",
    "name": "Evolved"
  },
  {
    "id": 1597,
    "slug": "enhancement_titanic",
    "name": "Titanic"
  },
  {
    "id": 1598,
    "slug": "unrelenting_eye",
    "name": "Unrelenting Eye"
  },
  {
    "id": 1599,
    "slug": "mana_draught",
    "name": "Mana Draught"
  },
  {
    "id": 1600,
    "slug": "rippers_lash",
    "name": "Ripper's Lash"
  },
  {
    "id": 1601,
    "slug": "crippling_crossbow",
    "name": "Crippling Crossbow"
  },
  {
    "id": 1602,
    "slug": "gale_guard",
    "name": "Gale Guard"
  },
  {
    "id": 1603,
    "slug": "gunpowder_gauntlets",
    "name": "Gunpowder Gauntlet"
  },
  {
    "id": 1604,
    "slug": "searing_signet",
    "name": "Searing Signet"
  },
  {
    "id": 1605,
    "slug": "serrated_shiv",
    "name": "Serrated Shiv"
  },
  {
    "id": 1606,
    "slug": "polliwog_charm",
    "name": "Pollywog Charm"
  },
  {
    "id": 1607,
    "slug": "magnifying_monocle",
    "name": "Magnifying Monocle"
  },
  {
    "id": 1608,
    "slug": "pyrrhic_cloak",
    "name": "Pyrrhic Cloak"
  },
  {
    "id": 1609,
    "slug": "madstone_bundle",
    "name": "Madstone Bundle"
  },
  {
    "id": 1610,
    "slug": "miniboss_minion_summoner",
    "name": "miniboss_minion_summoner"
  },
  {
    "id": 1637,
    "slug": "kobold_cup",
    "name": "Kobold Cup"
  },
  {
    "id": 1638,
    "slug": "dormant_curio",
    "name": "Dormant Curio"
  },
  {
    "id": 1639,
    "slug": "sisters_shroud",
    "name": "Sister's Shroud"
  },
  {
    "id": 1640,
    "slug": "jidi_pollen_bag",
    "name": "Jidi Pollen Bag"
  },
  {
    "id": 1641,
    "slug": "outworld_staff",
    "name": "Outworld Staff"
  },
  {
    "id": 1642,
    "slug": "dezun_bloodrite",
    "name": "Dezun Bloodrite"
  },
  {
    "id": 1643,
    "slug": "giant_maul",
    "name": "Giant's Maul"
  },
  {
    "id": 1644,
    "slug": "divine_regalia",
    "name": "Divine Regalia"
  },
  {
    "id": 1645,
    "slug": "divine_regalia_broken",
    "name": "Disgraced Regalia"
  },
  {
    "id": 1647,
    "slug": "enhancement_fierce",
    "name": "Fierce"
  },
  {
    "id": 1648,
    "slug": "enhancement_dominant",
    "name": "Dominant"
  },
  {
    "id": 1649,
    "slug": "enhancement_restorative",
    "name": "Restorative"
  },
  {
    "id": 1650,
    "slug": "enhancement_thick",
    "name": "Thick"
  },
  {
    "id": 1651,
    "slug": "enhancement_curious",
    "name": "Unleashed"
  },
  {
    "id": 1652,
    "slug": "furion_gold_bag",
    "name": "Bag of Gold"
  },
  {
    "id": 1715,
    "slug": "recipe",
    "name": "recipe_specialists_array"
  },
  {
    "id": 1716,
    "slug": "weighted_dice",
    "name": "Weighted Dice"
  },
  {
    "id": 1717,
    "slug": "ash_legion_shield",
    "name": "Ash Legion Shield"
  },
  {
    "id": 1718,
    "slug": "riftshadow_prism",
    "name": "Riftshadow Prism"
  },
  {
    "id": 1719,
    "slug": "metamorphic_mandible",
    "name": "Metamorphic Mandible"
  },
  {
    "id": 1720,
    "slug": "idol_of_screeauk",
    "name": "Idol of Scree'auk"
  },
  {
    "id": 1721,
    "slug": "flayers_bota",
    "name": "Flayer's Bota"
  },
  {
    "id": 1801,
    "slug": "caster_rapier",
    "name": "caster_rapier"
  },
  {
    "id": 1802,
    "slug": "tiara_of_selemene",
    "name": "Tiara of Selemene"
  },
  {
    "id": 1803,
    "slug": "doubloon",
    "name": "Doubloon"
  },
  {
    "id": 1804,
    "slug": "roshans_banner",
    "name": "Roshan's Banner"
  },
  {
    "id": 1805,
    "slug": "recipe",
    "name": "Parasma Recipe"
  },
  {
    "id": 1806,
    "slug": "devastator",
    "name": "Parasma"
  },
  {
    "id": 1808,
    "slug": "angels_demise",
    "name": "Khanda"
  },
  {
    "id": 1847,
    "slug": "splintmail",
    "name": "Splintmail"
  },
  {
    "id": 1848,
    "slug": "shawl",
    "name": "Shawl"
  },
  {
    "id": 1849,
    "slug": "wizard_hat",
    "name": "Wizard Hat"
  },
  {
    "id": 1850,
    "slug": "eldwurms_edda",
    "name": "Eldwurm's Edda"
  },
  {
    "id": 1851,
    "slug": "recipe",
    "name": "Essence Distiller Recipe"
  },
  {
    "id": 1852,
    "slug": "essence_distiller",
    "name": "Essence Distiller"
  },
  {
    "id": 1853,
    "slug": "recipe",
    "name": "Consecrated Wraps Recipe"
  },
  {
    "id": 1854,
    "slug": "consecrated_wraps",
    "name": "Consecrated Wraps"
  },
  {
    "id": 1855,
    "slug": "recipe",
    "name": "Crella's Crozier Recipe"
  },
  {
    "id": 1856,
    "slug": "crellas_crozier",
    "name": "Crella's Crozier"
  },
  {
    "id": 1857,
    "slug": "recipe",
    "name": "recipe_hydras_breath"
  },
  {
    "id": 1858,
    "slug": "hydras_breath",
    "name": "Hydra's Breath"
  },
  {
    "id": 1859,
    "slug": "spellslinger",
    "name": "Spellslinger"
  },
  {
    "id": 1860,
    "slug": "prophets_pendulum",
    "name": "Prophet's Pendulum"
  },
  {
    "id": 1861,
    "slug": "stonefeather_satchel",
    "name": "Stonefeather Satchel"
  },
  {
    "id": 1862,
    "slug": "enchanters_bauble",
    "name": "Enchanter's Bauble"
  },
  {
    "id": 1863,
    "slug": "harmonizer",
    "name": "Harmonizer"
  },
  {
    "id": 1864,
    "slug": "conjurers_catalyst",
    "name": "Conjurer's Catalyst"
  },
  {
    "id": 1865,
    "slug": "enhancement_vital",
    "name": "Vital"
  },
  {
    "id": 1866,
    "slug": "enhancement_hulking",
    "name": "Hulking"
  },
  {
    "id": 1867,
    "slug": "enhancement_manic",
    "name": "Manic"
  },
  {
    "id": 1868,
    "slug": "foragers_kit",
    "name": "Forager's Kit"
  },
  {
    "id": 1869,
    "slug": "foragers_health",
    "name": "Vital Toadstool"
  },
  {
    "id": 1870,
    "slug": "foragers_stats",
    "name": "Ironwood Nut"
  },
  {
    "id": 1871,
    "slug": "foragers_mana",
    "name": "Tomo'kan Ringcap"
  },
  {
    "id": 1872,
    "slug": "chasm_stone",
    "name": "Chasm Stone"
  },
  {
    "id": 1873,
    "slug": "partisans_brand",
    "name": "Partisan's Brand"
  },
  {
    "id": 1874,
    "slug": "enhancement_nimble",
    "name": "Nimble"
  },
  {
    "id": 1875,
    "slug": "tidehunter_fish",
    "name": "Leviathan's Fish"
  },
  {
    "id": 2091,
    "slug": "tier1_token",
    "name": "Tier 1 Token"
  },
  {
    "id": 2092,
    "slug": "tier2_token",
    "name": "Tier 2 Token"
  },
  {
    "id": 2093,
    "slug": "tier3_token",
    "name": "Tier 3 Token"
  },
  {
    "id": 2094,
    "slug": "tier4_token",
    "name": "Tier 4 Token"
  },
  {
    "id": 2095,
    "slug": "tier5_token",
    "name": "Tier 5 Token"
  },
  {
    "id": 2096,
    "slug": "vindicators_axe",
    "name": "Vindicator's Axe"
  },
  {
    "id": 2097,
    "slug": "duelist_gloves",
    "name": "Duelist Gloves"
  },
  {
    "id": 2190,
    "slug": "dandelion_amulet",
    "name": "Dandelion Amulet"
  },
  {
    "id": 2192,
    "slug": "martyrs_plate",
    "name": "Martyr's Plate"
  },
  {
    "id": 2193,
    "slug": "gossamer_cape",
    "name": "Gossamer Cape"
  },
  {
    "id": 4204,
    "slug": "famango",
    "name": "Healing Lotus"
  },
  {
    "id": 4205,
    "slug": "great_famango",
    "name": "Great Healing Lotus"
  },
  {
    "id": 4206,
    "slug": "greater_famango",
    "name": "Greater Healing Lotus"
  },
  {
    "id": 4300,
    "slug": "ofrenda",
    "name": "Beloved Memory"
  },
  {
    "id": 4301,
    "slug": "ofrenda_shovel",
    "name": "Scrying Shovel"
  },
  {
    "id": 4302,
    "slug": "ofrenda_pledge",
    "name": "Forebearer's Fortune"
  }
] as const satisfies readonly DotaItem[];

const ITEM_BY_ID = new Map<number, DotaItem>(DOTA_ITEMS.map((item) => [item.id, item] as const));

export function itemById(id: number) {
  return ITEM_BY_ID.get(id);
}

export function itemImage(id: number) {
  const item = itemById(id);
  return item ? `/items/${item.slug}.png` : null;
}
