import { useState } from "react";
import { Activity, RefreshCw, CircleAlert, Server } from "lucide-react";
import type { ReplayMonitorSnapshot } from "@/lib/replay/monitor-types";
import type { Messages } from "../i18n";
import { adminBytes, adminDate, adminNumber, adminStatus, adminText, unitState, useAccountRead, type ServiceMonitor } from "../admin";
import { CopyValue } from "./Shared";
import { AdminReadState } from "./AdminShared";

const names: Record<string, [string,string]> = {
  "dota2notes-api.service":["API","API"], "dota2notes.service":["وب","Website"],
  "dota2notes-replay.service":["پردازش ریپلی","Replay worker"], "dota2notes-replay.timer":["زمان‌بندی ریپلی","Replay timer"],
  "dota2notes-sync.service":["دریافت مچ","Match fetch worker"], "dota2notes-sync-manual.timer":["دریافت دستی مچ","Manual match fetch timer"],
  "dota2notes-performance-reference.service":["مرجع آماری","Reference worker"], "dota2notes-performance-reference.timer":["زمان‌بندی مرجع","Reference timer"],
  "dota2notes-monitor.service":["ثبت وضعیت سرویس‌ها","Service collector"], "dota2notes-monitor.timer":["زمان‌بندی مانیتور","Monitor timer"],
  "dota2notes-images.service":["ساخت تصاویر","Image worker"], "dota2notes-images.timer":["زمان‌بندی تصاویر","Image timer"],
  "dota2notes-opendota-parse.service":["Parse خارجی","External parse worker"], "dota2notes-opendota-parse.timer":["زمان‌بندی Parse","External parse timer"],
};
export function AdminServices({ t }: {t:Messages}) {
  const read = useAccountRead<{monitor:ServiceMonitor}>("/api/admin/service-monitor",true,30000);
  const monitor = read.data?.monitor;
  const [selected,setSelected] = useState("dota2notes-api.service"), [filter,setFilter] = useState("all");
  const current = monitor?.units.find(unit=>unit.id === selected) || monitor?.units[0];
  const logs = current?.logs.filter(log=>filter === "all" || log.priority <= (filter === "error" ? 3 : 4)) || [];
  const issues = monitor?.units.filter(unit=>unitState(unit) === "failed").length || 0;
  return <div className="screen-stack"><div className="admin-toolbar"><span className="admin-live"><i className={`signal-dot ${issues ? "signal-error" : !monitor || monitor.stale ? "signal-retry" : ""}`}/>{adminText(t,"آخرین گزارش","Snapshot")}: {adminDate(monitor?.capturedAt,t)}</span><button className="secondary-button" disabled={read.busy} onClick={read.refresh}><RefreshCw size={16}/>{t.refresh}</button></div><AdminReadState error={read.error} busy={read.busy} hasData={!!monitor} t={t}/>
    {monitor && <>{(monitor.stale || monitor.snapshotError) && <div className="admin-warning" role="status"><CircleAlert size={20}/><p>{adminText(t,"گزارش وضعیت سرویس‌ها تازه نیست؛ timer مانیتور را بررسی کن. آمار صف‌ها جداگانه از دیتابیس دریافت شده است.","The service snapshot is unavailable or stale. Check the monitor timer. Queue totals were read separately from the database.")}</p></div>}
    <div className="service-card-grid">{monitor.units.map(unit=>{
      const status = unitState(unit), label = names[unit.id];
      return <button key={unit.id} className={`panel service-card ${selected === unit.id ? "selected" : ""} state-${status}`} aria-pressed={selected === unit.id} onClick={()=>setSelected(unit.id)}><span><Server size={18}/><strong>{label ? adminText(t,...label) : unit.id.replace(/\.service$|\.timer$/g,"")}</strong></span><code>{unit.id}</code><span className="service-state"><i/>{status === "inactive" ? adminText(t,"غیرفعال","Inactive") : status === "completed" ? adminText(t,"اجرای قبلی موفق","Last run succeeded") : adminStatus(status,t)}</span><small>{adminText(t,"خروج","Exit")}: {unit.properties.ExecMainStatus || "—"} · {unit.properties.SubState || "—"}</small></button>;
    })}</div>
    <section className="panel account-section"><h2>{adminText(t,"صف‌های پردازش","Processing queues")}</h2><div className="admin-queue-grid">{monitor.queues.map(q=><div className="queue-count" key={`${q.source}:${q.status}`}><span>{q.source} · {adminStatus(q.status,t)}</span><strong>{adminNumber(q.total,t)}</strong></div>)}</div>{!!monitor.failures.length && <details className="admin-disclosure"><summary>{adminText(t,"آخرین خطاهای صف","Recent queue failures")}</summary><div className="admin-event-list">{monitor.failures.map((failure,index)=><div key={index}><b>{failure.source}</b><time>{adminDate(failure.at,t)}</time><code>{failure.detail}</code></div>)}</div></details>}</section>
    {current && <section className="panel account-section"><div className="section-heading"><h2><Activity size={18}/> <bdi>{current.id}</bdi></h2><select aria-label={adminText(t,"فیلتر لاگ","Log filter")} value={filter} onChange={event=>setFilter(event.target.value)}><option value="all">{t.all}</option><option value="warning">Warning + Error</option><option value="error">Error</option></select></div><dl className="account-facts"><div><dt>{adminText(t,"آخرین اجرا","Last run")}</dt><dd>{adminDate(current.properties.ExecMainExitTimestamp || current.properties.ActiveEnterTimestamp,t)}</dd></div><div><dt>{adminText(t,"اجرای بعدی","Next tick")}</dt><dd>{adminDate(current.properties.NextElapseUSecRealtime,t)}</dd></div><div><dt>{adminText(t,"وضعیت","State")}</dt><dd><bdi>{current.properties.ActiveState} / {current.properties.SubState}</bdi></dd></div></dl>
    {current.error && <p className="admin-warning">{current.error}</p>}<div className="admin-log" role="log" aria-label={`${adminText(t,"لاگ","Logs")} ${current.id}`}>{logs.map((log,index)=><p key={`${log.at}:${index}`} className={log.priority<=3 ? "log-error" : log.priority===4 ? "log-warning" : ""}><time>{adminDate(log.at,t)}</time><b>{log.priority<=3 ? "ERROR" : log.priority===4 ? "WARN" : "INFO"}</b><span dir="auto">{log.message}</span></p>)}{!logs.length && <p>{adminText(t,"لاگی در این گزارش ثبت نشده است.","No log entries in this snapshot.")}</p>}</div><small className="muted">{adminText(t,"حداکثر ۳۵ خط اخیر هر سرویس. گزارش هر دقیقه ثبت می‌شود؛ worker مقطعی پس از اجرای موفق غیرفعال می‌شود.","Up to 35 recent lines per service. Snapshots are collected every minute; a successful oneshot worker returns to inactive.")}</small></section>}
    </>}
  </div>;
}
export function AdminReplayMonitor({ t }: {t:Messages}) {
  const [query,setQuery] = useState(""), [selected,setSelected] = useState("");
  const read = useAccountRead<{monitor:ReplayMonitorSnapshot}>(`/api/admin/replay-monitor${selected ? `?matchId=${encodeURIComponent(selected)}` : ""}`,true,5000);
  const m = read.data?.monitor;
  return <div className="screen-stack"><div className="admin-toolbar"><form className="admin-inline-form" onSubmit={event=>{event.preventDefault();setSelected(query.trim());}}><input aria-label={t.matchId} inputMode="numeric" pattern="[0-9]+" value={query} onChange={event=>setQuery(event.target.value)} placeholder={t.matchId}/><button className="secondary-button">{t.search}</button>{selected && <button type="button" className="secondary-button" onClick={()=>{setQuery("");setSelected("");}}>{t.all}</button>}</form><button className="secondary-button" disabled={read.busy} onClick={read.refresh}><RefreshCw size={16}/>{t.refresh}</button></div><AdminReadState error={read.error} busy={read.busy} hasData={!!m} t={t}/>
    {m && <><section className="panel account-section"><div className="section-heading"><h2>{adminText(t,"دانلود و پردازش ریپلی","Replay transfer & processing")}</h2><time>{adminDate(m.capturedAt,t)}</time></div><div className="admin-queue-grid">{m.totals.map(total=><div className="queue-count" key={total.status}><span>{adminStatus(total.status,t)}</span><strong>{total.count}</strong></div>)}</div><p className="muted">{adminText(t,"دریافت ثبت‌شده","Recorded transfer")}: <bdi>{adminBytes(m.totals.reduce((n,item)=>n+Number(item.transfer_bytes),0))}</bdi> · {adminText(t,"آپلود ثبت‌شده","Recorded upload")}: <bdi>{adminBytes(m.totals.reduce((n,item)=>n+Number(item.upload_bytes),0))}</bdi></p>
    <div className="admin-table-scroll"><table className="admin-data-table"><thead><tr><th>{t.matchId}</th><th>{adminText(t,"مرحله","Stage")}</th><th>{adminText(t,"پیشرفت","Progress")}</th><th>{adminText(t,"سرعت","Speed")}</th><th>{adminText(t,"تلاش","Attempt")}</th><th>{adminText(t,"آرشیو","Archive")}</th><th>{adminText(t,"تلاش بعدی","Next retry")}</th></tr></thead><tbody>{m.jobs.map(job=><tr key={job.match_id}><td><CopyValue value={job.match_id} t={t}/><button className="secondary-button" onClick={()=>{setQuery(job.match_id);setSelected(job.match_id);}}>{t.details}</button></td><td><span className={`admin-status state-${job.status}`}>{adminStatus(job.phase,t)}</span><small>{job.intent} · {adminStatus(job.status,t)}</small></td><td><progress aria-label={`${t.analysisDownload} ${job.match_id}`} max={Number(job.total_bytes)||1} value={Number(job.total_bytes) ? Number(job.downloaded_bytes) : 0}/><bdi>{adminBytes(job.downloaded_bytes)} / {adminBytes(job.total_bytes)}</bdi></td><td><bdi>{job.phase === "downloading" ? `${adminBytes(job.download_bps)}/s` : "—"}</bdi></td><td>{job.attempts}</td><td>{job.archive_status}</td><td>{job.status === "pending" ? adminDate(job.run_after,t) : "—"}</td></tr>)}</tbody></table></div>
    {m.jobs.map(job=><details className="admin-disclosure" key={job.match_id}><summary>{job.match_id} · {t.details}</summary><dl className="account-facts">{[[adminText(t,"آخرین فعالیت","Heartbeat"),job.heartbeat_at],[adminText(t,"شروع مرحله","Stage started"),job.phase_started_at],[adminText(t,"مهلت تلاش","Retry deadline"),job.retry_deadline_at]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{adminDate(value,t)}</dd></div>)}</dl><p>{adminText(t,"فایل موقت کامل","Complete spool")}: {job.spool_complete ? "✓" : "—"}</p><p><code>{job.error_code} {job.error_message}</code></p><p><bdi>{job.last_endpoint} {job.last_address}</bdi></p></details>)}</section>
    <section className="panel account-section"><h2>{adminText(t,"مسیرهای اتصال","Connection routes")}</h2><div className="admin-event-list">{m.routes.map(route=><div key={`${route.endpoint}:${route.address}`}><bdi>{route.endpoint} · {route.address}</bdi><span>{adminText(t,"خطاها","Failures")}: {route.failures}</span><time>{adminDate(route.last_success_at,t)}</time><code>{route.last_error_code || "—"}</code>{route.open_until && <span>{adminText(t,"توقف تا","Paused until")}: {adminDate(route.open_until,t)}</span>}</div>)}</div></section>
    <section className="panel account-section"><h2>{adminText(t,"رویدادهای اخیر","Recent events")}</h2><div className="admin-log" role="log">{m.events.map((event,index)=><p key={index}><time>{adminDate(event.created_at,t)}</time><CopyValue value={event.match_id} t={t}/><code>{event.phase} · {event.code}</code><span>{event.detail}</span>{event.endpoint && <bdi>{event.endpoint} @ {event.address}</bdi>}{event.http_status && <span>HTTP {event.http_status}</span>}</p>)}</div><small className="muted">{adminText(t,"۵۰ کار اخیر و حداکثر ۱۰۰ رویداد؛ دریافت وضعیت فقط در این تب فعال است.","50 recent jobs and up to 100 events. Polling runs only while this tab is visible.")}</small></section></>}
  </div>;
}
