import {
  deleteStoredObject,
  isStorageNotFound,
  uploadStoredObject,
} from "@/lib/storage/client";
import { getStorageConfig } from "@/lib/storage/config";
import {
  createGeneratedMatchImageKey,
  makePublicImageUrl,
} from "@/lib/storage/media";
import { MediaError } from "./errors";
import {
  listMatchImages,
  replaceGeneratedMatchImages,
} from "./repository";
import {
  type GeneratedMatchImageArtifact,
  validateGeneratedMatchImages,
} from "./validation";

function serializeImage(image: {
  id: string;
  originalName: string;
  mimeType: string;
  sizeBytes: number;
  width: number | null;
  height: number | null;
  altText: string;
  sortOrder: number;
  objectKey: string;
  createdAt: Date;
}) {
  return {
    id: image.id,
    publicUrl: makePublicImageUrl(image.objectKey),
    originalName: image.originalName,
    mimeType: image.mimeType,
    sizeBytes: image.sizeBytes,
    width: image.width,
    height: image.height,
    altText: image.altText,
    sortOrder: image.sortOrder,
    createdAt: image.createdAt.toISOString(),
  };
}

async function bestEffortDelete(objectKey: string) {
  try {
    await deleteStoredObject(objectKey);
  } catch (error) {
    if (!isStorageNotFound(error)) {
      console.warn("Unable to clean up generated match image", { objectKey });
    }
  }
}

/**
 * Publishes one to three images that were generated by trusted backend code.
 * Bytes are sent from memory to object storage; this function never creates a
 * temporary file and never exposes storage credentials or upload URLs.
 */
export async function publishGeneratedMatchImages(
  matchId: string,
  artifacts: GeneratedMatchImageArtifact[],
) {
  const config = getStorageConfig();
  const generated = validateGeneratedMatchImages(
    artifacts,
    config.maxGeneratedImageBytes,
  );
  const uploaded: Array<{
    objectKey: string;
    artifact: (typeof generated)[number];
    sortOrder: number;
  }> = [];

  try {
    for (const [index, artifact] of generated.entries()) {
      const sortOrder = index + 1;
      const objectKey = createGeneratedMatchImageKey(
        matchId,
        sortOrder,
        artifact.mimeType,
      );
      await uploadStoredObject(objectKey, artifact.mimeType, artifact.bytes);
      uploaded.push({ objectKey, artifact, sortOrder });
    }
  } catch {
    await Promise.allSettled(
      uploaded.map((image) => bestEffortDelete(image.objectKey)),
    );
    throw new MediaError(
      502,
      "storage_unavailable",
      "انتشار تصویر تولیدشده در فضای ذخیره‌سازی انجام نشد",
    );
  }

  let replaced;
  try {
    replaced = await replaceGeneratedMatchImages(
      matchId,
      uploaded.map(({ objectKey, artifact, sortOrder }) => ({
        objectKey,
        originalName: artifact.fileName,
        mimeType: artifact.mimeType,
        sizeBytes: artifact.bytes.byteLength,
        width: artifact.width,
        height: artifact.height,
        altText: artifact.altText,
        sortOrder,
      })),
    );
  } catch (error) {
    await Promise.allSettled(
      uploaded.map((image) => bestEffortDelete(image.objectKey)),
    );
    throw error;
  }

  await Promise.allSettled(
    replaced.previousObjectKeys.map(bestEffortDelete),
  );

  return replaced.images.map(serializeImage);
}

export async function getPublicMatchImages(matchId: string) {
  const images = await listMatchImages(matchId);
  return images.map(serializeImage);
}
